"use client";

import type { Customer, JobPriority, JobSheet, JobStatus, Vehicle } from "@dvcs/types";
import { collection, doc, getDocs, query, serverTimestamp, updateDoc, where, writeBatch } from "firebase/firestore";
import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { useAuth } from "@/lib/auth-context";
import { firebaseClient } from "@/lib/firebase-client";

const stages:Array<[JobStatus,string]>=[["check_in","Check-In"],["inspection","Inspection"],["estimate_pending","Estimate Pending"],["approved","Approved"],["in_progress","In Progress"],["quality_check","Quality Check"],["ready","Ready"],["delivered","Delivered"]];
const services=["General Service","Periodic Maintenance","Running Repair","Accidental Repair","Electrical Diagnosis","AC Service","Tyre & Wheel Service","Inspection Only","Other"];
type Draft={customerId:string;vehicleId:string;serviceType:string;priority:JobPriority;odometer:string;fuelLevel:string;promisedAt:string;complaints:string;internalNotes:string};
const emptyDraft:Draft={customerId:"",vehicleId:"",serviceType:"General Service",priority:"normal",odometer:"",fuelLevel:"50",promisedAt:"",complaints:"",internalNotes:""};
const statusLabel=(status:JobStatus)=>stages.find(([value])=>value===status)?.[1]??"Cancelled";

export default function JobsPage(){
 const {user,activeCompanyId,activeBranchId,activeBranch}=useAuth();
 const [jobs,setJobs]=useState<JobSheet[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[vehicles,setVehicles]=useState<Vehicle[]>([]);
 const [selectedId,setSelectedId]=useState<string|null>(null),[filter,setFilter]=useState<JobStatus|"active"|"all">("active"),[search,setSearch]=useState("");
 const [loading,setLoading]=useState(true),[showForm,setShowForm]=useState(false),[submitting,setSubmitting]=useState(false),[error,setError]=useState<string|null>(null);
 const [draft,setDraft]=useState<Draft>(emptyDraft);
 const load=useCallback(async()=>{if(!activeCompanyId||!activeBranchId)return;setLoading(true);try{const [jobDocs,customerDocs,vehicleDocs]=await Promise.all([getDocs(query(collection(firebaseClient.db,"jobSheets"),where("companyId","==",activeCompanyId),where("branchId","==",activeBranchId))),getDocs(query(collection(firebaseClient.db,"customers"),where("companyId","==",activeCompanyId),where("branchId","==",activeBranchId))),getDocs(query(collection(firebaseClient.db,"vehicles"),where("companyId","==",activeCompanyId),where("branchId","==",activeBranchId)))]);const nextJobs=jobDocs.docs.map((item)=>({...item.data(),id:item.id} as JobSheet)).sort((a,b)=>b.jobNumber.localeCompare(a.jobNumber));setJobs(nextJobs);setCustomers(customerDocs.docs.map((item)=>({...item.data(),id:item.id} as Customer)).filter(({status})=>status==="active"));setVehicles(vehicleDocs.docs.map((item)=>({...item.data(),id:item.id} as Vehicle)).filter(({status})=>status==="active"));setSelectedId((current)=>current&&nextJobs.some(({id})=>id===current)?current:(nextJobs[0]?.id??null));}catch(reason){setError(reason instanceof Error?reason.message:"Unable to load job cards.");}finally{setLoading(false);}},[activeBranchId,activeCompanyId]);
 useEffect(()=>{void load();},[load]);
 const filtered=useMemo(()=>{const term=search.trim().toLowerCase();return jobs.filter((job)=>{const matchesFilter=filter==="all"||(filter==="active"&&!(["delivered","cancelled"] as JobStatus[]).includes(job.status))||job.status===filter;return matchesFilter&&(!term||`${job.jobNumber} ${job.customerName} ${job.registrationNumber} ${job.vehicleLabel}`.toLowerCase().includes(term));});},[filter,jobs,search]);
 const selected=jobs.find(({id})=>id===selectedId)??null;const customerVehicles=vehicles.filter(({customerId})=>customerId===draft.customerId);const selectedVehicle=vehicles.find(({id})=>id===draft.vehicleId);const selectedCustomer=customers.find(({id})=>id===draft.customerId);
 const counts={active:jobs.filter(({status})=>!(["delivered","cancelled"] as JobStatus[]).includes(status)).length,progress:jobs.filter(({status})=>status==="in_progress").length,ready:jobs.filter(({status})=>status==="ready").length,urgent:jobs.filter(({priority,status})=>priority!=="normal"&&!(["delivered","cancelled"] as JobStatus[]).includes(status)).length};
 function openNew(){setDraft(emptyDraft);setError(null);setShowForm(true);}
 async function createJob(event:FormEvent){event.preventDefault();if(!user||!activeCompanyId||!activeBranchId||!selectedCustomer||!selectedVehicle)return;const complaints=draft.complaints.split("\n").map((value)=>value.trim()).filter(Boolean);if(!draft.odometer||complaints.length===0){setError("Enter the current Odometer and at least one Customer Complaint.");return;}setSubmitting(true);setError(null);try{const ref=doc(collection(firebaseClient.db,"jobSheets"));const now=serverTimestamp();const date=new Date().toISOString().slice(2,10).replaceAll("-","");const jobNumber=`JC-${date}-${ref.id.slice(0,5).toUpperCase()}`;await writeBatch(firebaseClient.db).set(ref,{companyId:activeCompanyId,branchId:activeBranchId,jobNumber,customerId:selectedCustomer.id,vehicleId:selectedVehicle.id,customerName:selectedCustomer.name,vehicleLabel:`${selectedVehicle.make} ${selectedVehicle.model}`,registrationNumber:selectedVehicle.registrationNumber,status:"check_in",priority:draft.priority,serviceType:draft.serviceType,odometer:Number(draft.odometer),fuelLevel:Number(draft.fuelLevel),complaints,internalNotes:draft.internalNotes.trim(),promisedAt:draft.promisedAt||null,checkedInAt:now,assignedTechnicianIds:[],estimateTotal:0,invoiceTotal:0,createdAt:now,createdBy:user.uid,updatedAt:now,updatedBy:user.uid}).commit();setShowForm(false);setDraft(emptyDraft);await load();setSelectedId(ref.id);}catch(reason){setError(reason instanceof Error?reason.message:"Unable to create the job card.");}finally{setSubmitting(false);}}
 async function setStatus(status:JobStatus){if(!user||!selected)return;setSubmitting(true);setError(null);try{await updateDoc(doc(firebaseClient.db,"jobSheets",selected.id),{status,deliveredAt:status==="delivered"?serverTimestamp():selected.deliveredAt??null,updatedAt:serverTimestamp(),updatedBy:user.uid});await load();}catch(reason){setError(reason instanceof Error?reason.message:"Unable to update job status.");}finally{setSubmitting(false);}}
 const nextStatus=selected?stages[stages.findIndex(([value])=>value===selected.status)+1]:undefined;
 return <main className="content jobs-page"><div className="dashboard-heading"><div><span className="heading-kicker">Service Operations</span><h1>Job Cards</h1><p className="muted">Live workshop flow for {activeBranch?.name??"this branch"}.</p></div><button className="quick-action quick-action--enabled" onClick={openNew}><strong>+</strong> New Job Card</button></div>
 {error&&!showForm?<div className="alert alert--error module-alert">{error}<button onClick={()=>setError(null)}>×</button></div>:null}<section className="job-summary"><div><span>Active Jobs</span><strong>{counts.active}</strong></div><div><span>In Progress</span><strong>{counts.progress}</strong></div><div><span>Ready For Delivery</span><strong>{counts.ready}</strong></div><div className={counts.urgent?"has-warning":""}><span>Urgent / Breakdown</span><strong>{counts.urgent}</strong></div></section>
 <section className="job-workspace"><div className="job-directory"><div className="job-toolbar"><div className="search-box"><span>⌕</span><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search Job, Customer or Registration"/></div><select value={filter} onChange={(e)=>setFilter(e.target.value as typeof filter)}><option value="active">Active Jobs</option><option value="all">All Jobs</option>{stages.map(([value,label])=><option key={value} value={value}>{label}</option>)}<option value="cancelled">Cancelled</option></select></div><div className="job-list">{loading?<div className="list-state"><span className="spinner"/>Loading Job Cards…</div>:filtered.length===0?<div className="list-state list-state--empty"><strong>{jobs.length?"No Matching Job Cards":"Service Reception Is Ready"}</strong><p>{jobs.length?"Try another search or status filter.":"Create the first job card when a vehicle arrives."}</p></div>:filtered.map((job)=><button key={job.id} className={`job-row ${selectedId===job.id?"is-selected":""}`} onClick={()=>setSelectedId(job.id)}><span className={`priority-dot priority-${job.priority}`}/><span><strong>{job.registrationNumber}</strong><small>{job.customerName} · {job.vehicleLabel}</small><em>{job.jobNumber}</em></span><span className={`job-status status-${job.status}`}>{statusLabel(job.status)}</span></button>)}</div></div>
 <aside className="job-detail">{selected?<><div className="job-detail-head"><div><span className="heading-kicker">{selected.jobNumber}</span><h2>{selected.registrationNumber}</h2><p>{selected.vehicleLabel} · {selected.customerName}</p></div><span className={`job-status status-${selected.status}`}>{statusLabel(selected.status)}</span></div><div className="job-stage-track">{stages.map(([value,label],index)=>{const current=stages.findIndex(([item])=>item===selected.status);return <div key={value} className={index<current?"is-done":index===current?"is-current":""}><i/><span>{label}</span></div>})}</div><div className="job-info-grid"><div><span>Service Type</span><strong>{selected.serviceType}</strong></div><div><span>Priority</span><strong>{selected.priority.charAt(0).toUpperCase()+selected.priority.slice(1)}</strong></div><div><span>Odometer</span><strong>{selected.odometer.toLocaleString("en-IN")} km</strong></div><div><span>Fuel Level</span><strong>{selected.fuelLevel}%</strong></div><div><span>Promised Delivery</span><strong>{selected.promisedAt?new Date(selected.promisedAt).toLocaleString("en-IN"):"Not Set"}</strong></div><div><span>Estimate</span><strong>{selected.estimateTotal?`₹${selected.estimateTotal.toLocaleString("en-IN")}`:"Pending"}</strong></div></div><section className="complaint-panel"><span className="heading-kicker">Customer Complaints</span><ol>{selected.complaints.map((complaint,index)=><li key={`${complaint}-${index}`}>{complaint}</li>)}</ol></section>{selected.internalNotes?<section className="job-note"><span>Internal Notes</span><p>{selected.internalNotes}</p></section>:null}<div className="job-detail-actions"><button className="cancel-job" disabled={submitting||selected.status==="delivered"||selected.status==="cancelled"} onClick={()=>void setStatus("cancelled")}>Cancel Job</button>{nextStatus?<button className="advance-job" disabled={submitting} onClick={()=>void setStatus(nextStatus[0])}>Move To {nextStatus[1]} <span>→</span></button>:null}</div></>:<div className="detail-empty"><h2>Select A Job Card</h2><p>Vehicle, complaints and workshop status will appear here.</p></div>}</aside></section>
 {showForm?<div className="modal-backdrop" onMouseDown={(e)=>{if(e.target===e.currentTarget&&!submitting)setShowForm(false)}}><form className="module-modal job-modal" onSubmit={createJob}><header className="modal-header"><div><span className="heading-kicker">Vehicle Check-In</span><h2>New Job Card</h2></div><button type="button" onClick={()=>setShowForm(false)}>×</button></header>{error?<div className="alert alert--error modal-alert">{error}</div>:null}<div className="form-grid"><label>Customer *<select value={draft.customerId} onChange={(e)=>setDraft({...draft,customerId:e.target.value,vehicleId:""})} required><option value="">Select Customer</option>{customers.map((customer)=><option key={customer.id} value={customer.id}>{customer.name} · {customer.phone}</option>)}</select></label><label>Vehicle *<select value={draft.vehicleId} onChange={(e)=>{const vehicle=vehicles.find(({id})=>id===e.target.value);setDraft({...draft,vehicleId:e.target.value,odometer:vehicle?.odometer?String(vehicle.odometer):draft.odometer})}} disabled={!draft.customerId} required><option value="">Select Vehicle</option>{customerVehicles.map((vehicle)=><option key={vehicle.id} value={vehicle.id}>{vehicle.registrationNumber} · {vehicle.make} {vehicle.model}</option>)}</select></label><label>Service Type<select value={draft.serviceType} onChange={(e)=>setDraft({...draft,serviceType:e.target.value})}>{services.map((value)=><option key={value}>{value}</option>)}</select></label><label>Priority<select value={draft.priority} onChange={(e)=>setDraft({...draft,priority:e.target.value as JobPriority})}><option value="normal">Normal</option><option value="urgent">Urgent</option><option value="breakdown">Breakdown</option></select></label><label>Current Odometer (km) *<input type="number" min="0" value={draft.odometer} onChange={(e)=>setDraft({...draft,odometer:e.target.value})} required/></label><label>Fuel Level<select value={draft.fuelLevel} onChange={(e)=>setDraft({...draft,fuelLevel:e.target.value})}>{[0,10,25,50,75,100].map((value)=><option key={value} value={value}>{value}%</option>)}</select></label><label>Promised Delivery<input type="datetime-local" value={draft.promisedAt} onChange={(e)=>setDraft({...draft,promisedAt:e.target.value})}/></label><label className="span-2">Customer Complaints *<textarea rows={4} value={draft.complaints} onChange={(e)=>setDraft({...draft,complaints:e.target.value})} placeholder={"Enter one complaint per line\nExample: Engine noise during cold start"} required/></label><label className="span-2">Internal Workshop Notes<textarea rows={3} value={draft.internalNotes} onChange={(e)=>setDraft({...draft,internalNotes:e.target.value})}/></label></div><footer className="modal-footer"><button type="button" className="cancel-button" onClick={()=>setShowForm(false)}>Cancel</button><button className="dv-button" disabled={submitting||!draft.customerId||!draft.vehicleId}>{submitting?"Creating…":"Create Job Card"}</button></footer></form></div>:null}</main>;
}
