"use client";

import type { CommunicationEntitlement, Company } from "@dvcs/types";
import { collection, doc, getDoc, getDocs, serverTimestamp, setDoc } from "firebase/firestore";
import { useEffect, useState } from "react";
import { useAuth } from "@/lib/auth-context";
import { firebaseClient } from "@/lib/firebase-client";

const blank=(companyId:string):CommunicationEntitlement=>({id:companyId,companyId,emailEnabled:true,pushEnabled:true,smsEnabled:false,whatsappEnabled:false,smsUnitRate:0.25,whatsappUnitRate:0.15,smsCredits:0,whatsappCredits:0,smsLowBalanceAt:100,whatsappLowBalanceAt:100,smsCredentialConfigured:false,whatsappCredentialConfigured:false,provider:"msg91",status:"active",createdAt:"",createdBy:"",updatedAt:"",updatedBy:""});

export default function CommunicationsAdmin(){
 const {user,profile,loading}=useAuth();const [companies,setCompanies]=useState<Company[]>([]),[items,setItems]=useState<Record<string,CommunicationEntitlement>>({}),[saving,setSaving]=useState<string|null>(null),[message,setMessage]=useState("");
 const allowed=profile?.platformRoles?.includes("platform_super_admin");
 useEffect(()=>{if(!allowed)return;void (async()=>{const snapshots=await getDocs(collection(firebaseClient.db,"companies"));const next=snapshots.docs.map((item)=>({...item.data(),id:item.id} as Company));setCompanies(next);const pairs=await Promise.all(next.map(async(company)=>{const snapshot=await getDoc(doc(firebaseClient.db,"communicationEntitlements",company.id));return [company.id,snapshot.exists()?({...snapshot.data(),id:snapshot.id} as CommunicationEntitlement):blank(company.id)] as const;}));setItems(Object.fromEntries(pairs));})();},[allowed]);
 if(loading)return <main className="state-page"><span className="spinner"/><h1>Loading Administration</h1></main>;
 if(!user||!allowed)return <main className="state-page"><div className="state-card"><h1>Super Admin Access Required</h1><p className="muted">This area is restricted to the Digital Viyabari platform administrator.</p></div></main>;
 function patch(companyId:string,values:Partial<CommunicationEntitlement>){setItems((current)=>({...current,[companyId]:{...(current[companyId]??blank(companyId)),...values}}));}
 async function save(companyId:string){const value=items[companyId];if(!value||!user)return;setSaving(companyId);setMessage("");try{const ref=doc(firebaseClient.db,"communicationEntitlements",companyId),existing=await getDoc(ref),now=serverTimestamp();await setDoc(ref,{...value,companyId,updatedAt:now,updatedBy:user.uid,...(!existing.exists()?{createdAt:now,createdBy:user.uid}:{})},{merge:true});setMessage("Communication entitlement saved securely.");}catch(reason){setMessage(reason instanceof Error?reason.message:"Unable to save configuration.");}finally{setSaving(null);}}
 return <main className="admin-page"><header className="admin-header"><div><span className="heading-kicker">Digital Viyabari Platform</span><h1>Communication Add-Ons</h1><p>Allocate paid WhatsApp and SMS channels, rates and credits by company.</p></div><a href="/dashboard">Return To Workspace</a></header>{message?<div className="alert admin-message">{message}</div>:null}<section className="admin-company-list">{companies.map((company)=>{const item=items[company.id]??blank(company.id);return <article key={company.id} className="admin-company-card"><div className="admin-company-title"><div><span>Company</span><h2>{company.name}</h2></div><span className={`source-chip ${item.status==="active"?"source-chip--company":"source-chip--default"}`}>{item.status}</span></div><div className="channel-grid"><Channel title="Push Notification" enabled={item.pushEnabled} free onChange={(value)=>patch(company.id,{pushEnabled:value})}/><Channel title="Email" enabled={item.emailEnabled} free onChange={(value)=>patch(company.id,{emailEnabled:value})}/><Channel title="WhatsApp" enabled={item.whatsappEnabled} onChange={(value)=>patch(company.id,{whatsappEnabled:value})}/><Channel title="SMS" enabled={item.smsEnabled} onChange={(value)=>patch(company.id,{smsEnabled:value})}/></div><div className="credit-grid"><NumberField label="WhatsApp Unit Rate (₹)" value={item.whatsappUnitRate} onChange={(value)=>patch(company.id,{whatsappUnitRate:value})}/><NumberField label="WhatsApp Credits" value={item.whatsappCredits} onChange={(value)=>patch(company.id,{whatsappCredits:value})}/><NumberField label="SMS Unit Rate (₹)" value={item.smsUnitRate} onChange={(value)=>patch(company.id,{smsUnitRate:value})}/><NumberField label="SMS Credits" value={item.smsCredits} onChange={(value)=>patch(company.id,{smsCredits:value})}/></div><div className="credential-note"><strong>VPS Credentials</strong><span>MSG91 secrets will be encrypted on the server and are never displayed here.</span></div><button className="dv-button admin-save" disabled={saving===company.id} onClick={()=>void save(company.id)}>{saving===company.id?"Saving…":"Save Allocation"}</button></article>})}</section></main>;
}
function Channel({title,enabled,free=false,onChange}:{title:string;enabled:boolean;free?:boolean;onChange:(value:boolean)=>void}){return <label className="channel-toggle"><input type="checkbox" checked={enabled} onChange={(event)=>onChange(event.target.checked)}/><span><strong>{title}</strong><small>{free?"Default Channel":"Paid Add-On"}</small></span></label>}
function NumberField({label,value,onChange}:{label:string;value:number;onChange:(value:number)=>void}){return <label>{label}<input type="number" min="0" step="0.01" value={value} onChange={(event)=>onChange(Number(event.target.value))}/></label>}
